import { expect, it, vi } from "vitest";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { OnboardingWizard } from "./onboarding-wizard";
import { invalidateAccountRequests } from "@/lib/auth/client";
import { ApiError } from "@energyrd/api-client";
it("no repite POST cuando no se pudo confirmar la creación", async () => {
  vi.mocked(saveOnboardingHome).mockRejectedValueOnce(new ApiError(0, "upstream secreto"));
  render(<OnboardingWizard onComplete={vi.fn()} />);
  fireEvent.click(screen.getByRole("button", { name: /Empezar/ }));
  for (const label of ["Nombre de la vivienda", "Provincia", "Municipio"]) fireEvent.change(screen.getByLabelText(label), { target: { value: "Casa" } });
  fireEvent.click(screen.getByRole("button", { name: /Guardar y continuar/ }));
  await screen.findByRole("heading", { name: /Distribuidora/ });
  fireEvent.click(screen.getByRole("button", { name: /Guardar y continuar/ }));
  await screen.findByRole("alert");
  expect(screen.getByRole("button", { name: /Guardar y continuar/ })).toBeDisabled();
  expect(screen.getByRole("link", { name: /Consultar mis viviendas/ })).toHaveAttribute("href", "/homes");
});
import { saveOnboardingHome, saveOnboardingContract, saveOnboardingGoal } from "@/lib/auth/onboarding";
vi.mock("@/lib/auth/onboarding", () => ({ saveOnboardingHome: vi.fn(), saveOnboardingContract: vi.fn(), saveOnboardingGoal: vi.fn() }));
const id = "11111111-1111-4111-8111-111111111111";
it("descarta una respuesta tardía sin avanzar al cambiar de cuenta", async () => {
  vi.mocked(saveOnboardingHome).mockImplementationOnce(async () => { invalidateAccountRequests(); return home as never; });
  render(<OnboardingWizard initialHome={home as never} onComplete={vi.fn()} />);
  fireEvent.click(screen.getByRole("button", { name: /Empezar/ }));
  fireEvent.click(screen.getByRole("button", { name: /Guardar y continuar/ }));
  await screen.findByRole("heading", { name: /Distribuidora/ });
  fireEvent.click(screen.getByRole("button", { name: /Guardar y continuar/ }));
  await screen.findByRole("alert");
  expect(screen.getByRole("heading", { name: /Distribuidora/ })).toBeInTheDocument();
  expect(screen.queryByRole("heading", { name: /Tipo de usuario/ })).not.toBeInTheDocument();
});
it("reintenta una etapa parcial con el id creado, sin repetir POST", async () => {
  vi.mocked(saveOnboardingHome).mockClear();
  vi.mocked(saveOnboardingHome).mockResolvedValueOnce(home as never).mockRejectedValueOnce(new Error("fallo parcial")).mockResolvedValueOnce(home as never);
  render(<OnboardingWizard onComplete={vi.fn()} />);
  fireEvent.click(screen.getByRole("button", { name: /Empezar/ }));
  for (const label of ["Nombre de la vivienda", "Provincia", "Municipio"]) fireEvent.change(screen.getByLabelText(label), { target: { value: "Casa" } });
  fireEvent.click(screen.getByRole("button", { name: /Guardar y continuar/ }));
  await screen.findByRole("heading", { name: /Distribuidora/ });
  fireEvent.click(screen.getByRole("button", { name: /Guardar y continuar/ }));
  await screen.findByRole("heading", { name: /Tipo de usuario/ });
  fireEvent.click(screen.getByRole("button", { name: /Guardar y continuar/ }));
  await screen.findByRole("alert");
  fireEvent.click(screen.getByRole("button", { name: /Guardar y continuar/ }));
  await screen.findByRole("heading", { name: /Perfil energético/ });
  expect(vi.mocked(saveOnboardingHome).mock.calls.filter(([homeId]) => homeId === null)).toHaveLength(1);
  expect(saveOnboardingHome).toHaveBeenLastCalledWith(id, { user_type: null });
});
const home = { id, name: "Casa", distributor: "EDESUR", province: "Santiago", municipality: "Santiago", sector: null, user_type: "Residencial", occupants: 2, has_ac: false, has_water_heater: null, has_pool: null, has_solar: null, has_inverter: null };
it("recorre seis etapas, persiste vivienda/contrato/meta y permite omitir datos opcionales", async () => {
  vi.mocked(saveOnboardingHome).mockResolvedValue(home as never);
  vi.mocked(saveOnboardingContract).mockResolvedValue({ home_id: id, account_number: "C-1", updated_at: "2026-01-01T00:00:00Z" });
  vi.mocked(saveOnboardingGoal).mockResolvedValue({ home_id: id, monthly_kwh: "200", monthly_amount_rd: null, updated_at: "2026-01-01T00:00:00Z" });
  const done = vi.fn(); render(<OnboardingWizard onComplete={done} />);
  fireEvent.click(screen.getByRole("button", { name: /Empezar/ }));
  fireEvent.change(screen.getByLabelText("Nombre de la vivienda"), { target: { value: "Casa" } });
  fireEvent.change(screen.getByLabelText("Provincia"), { target: { value: "Santiago" } });
  fireEvent.change(screen.getByLabelText("Municipio"), { target: { value: "Santiago" } });
  fireEvent.click(screen.getByRole("button", { name: /Guardar y continuar/ }));
  await screen.findByRole("heading", { name: /Distribuidora/ });
  fireEvent.click(screen.getByRole("button", { name: /Guardar y continuar/ }));
  await screen.findByRole("heading", { name: /Tipo de usuario/ });
  fireEvent.change(screen.getByLabelText("Tipo de usuario"), { target: { value: "Residencial" } });
  fireEvent.click(screen.getByRole("button", { name: /Guardar y continuar/ }));
  await screen.findByRole("heading", { name: /Perfil energético/ });
  fireEvent.change(screen.getByLabelText("Ocupantes"), { target: { value: "2" } });
  fireEvent.change(screen.getByLabelText("Aire acondicionado"), { target: { value: "no" } });
  fireEvent.click(screen.getByRole("button", { name: /Guardar y continuar/ }));
  await screen.findByRole("heading", { name: /Contrato/ });
  fireEvent.change(screen.getByLabelText("Número de cuenta"), { target: { value: "C-1" } });
  fireEvent.click(screen.getByRole("button", { name: /Guardar y continuar/ }));
  await screen.findByRole("heading", { name: /Meta mensual/ });
  fireEvent.change(screen.getByLabelText("Meta de consumo mensual (kWh)"), { target: { value: "200" } });
  fireEvent.click(screen.getByRole("button", { name: /Guardar y continuar/ }));
  await screen.findByRole("heading", { name: /Revisión/ });
  expect(saveOnboardingHome).toHaveBeenCalledWith(null, expect.objectContaining({ name: "Casa", province: "Santiago", municipality: "Santiago" }));
  expect(saveOnboardingHome).toHaveBeenCalledWith(id, expect.objectContaining({ user_type: "Residencial" }));
  expect(saveOnboardingHome).toHaveBeenCalledWith(id, expect.objectContaining({ occupants: 2, has_ac: false, has_pool: null }));
  expect(saveOnboardingContract).toHaveBeenCalledWith(id, "C-1");
  expect(saveOnboardingGoal).toHaveBeenCalledWith(id, { monthly_kwh: "200", monthly_amount_rd: null });
  fireEvent.click(screen.getByRole("button", { name: /Ir al panel/ }));
  expect(done).toHaveBeenCalledWith(id);
});
it("ante error conserva etapa y no completa ni muestra detalle upstream", async () => {
  vi.mocked(saveOnboardingHome).mockRejectedValue(new Error("fallo"));
  const done = vi.fn(); render(<OnboardingWizard onComplete={done} />);
  fireEvent.click(screen.getByRole("button", { name: /Empezar/ }));
  fireEvent.change(screen.getByLabelText("Nombre de la vivienda"), { target: { value: "Casa" } });
  fireEvent.change(screen.getByLabelText("Provincia"), { target: { value: "Santiago" } });
  fireEvent.change(screen.getByLabelText("Municipio"), { target: { value: "Santiago" } });
  fireEvent.click(screen.getByRole("button", { name: /Guardar y continuar/ }));
  await screen.findByRole("heading", { name: /Distribuidora/ });
  fireEvent.click(screen.getByRole("button", { name: /Guardar y continuar/ }));
  await waitFor(() => expect(screen.getByRole("alert")).toHaveTextContent("No se pudo guardar"));
  expect(done).not.toHaveBeenCalled();
});
it("reanuda vivienda propia incompleta con PATCH, no crea otra vivienda", async () => {
  vi.mocked(saveOnboardingHome).mockResolvedValue(home as never);
  render(<OnboardingWizard initialHome={home as never} onComplete={vi.fn()} />);
  fireEvent.click(screen.getByRole("button", { name: /Empezar/ }));
  expect(screen.getByLabelText("Provincia")).toHaveValue("Santiago");
  fireEvent.click(screen.getByRole("button", { name: /Guardar y continuar/ }));
  await screen.findByRole("heading", { name: /Distribuidora/ });
  fireEvent.click(screen.getByRole("button", { name: /Guardar y continuar/ }));
  await waitFor(() => expect(saveOnboardingHome).toHaveBeenCalledWith(id, expect.objectContaining({ distributor: "EDESUR" })));
});
